### PR TITLE
Adhering to current file naming convention(WIP)

### LINKED ISSUE #9: Broken module import
Dev server can't locate the SIgnUp from the App module.
## screenshot
broken-import

This is so because the App module is importing a wrong module due to typo error:  ```import SignUp from '../Login/SignUp';``` meanwhile the file's name is ``` ../Login/Signup```

## solution
Edit the import statement in App.js to reference the correct module's path ``` ../Login/Signup``` or maintain the current codebase's file case-naming convention which is the Pascal Case by renaming Signup.js to SignUp.js
I propose the file should fall within the scope of the convention.

### PR DESCRIPTION
**Pull request by ayamba-coder**
Fixes  #9 and it's a WIP till all files present in codebase have a common naming pattern

### CODE REVIEW

**Comment by ayamba-coder** [comment]
@FotieMConstant , @TatchumNono :
Considering to working on these, i found some files in the codebase and would love to hear from you if they necessarily should implement this pattern
-Copyright.js -> CopyRight.js
-serviceWorker.js -> ServiceWorker.js
-setupTests.js -> SetupTests.js
-Navbar.js -> NavBar.js

**Comment by FotieMConstant** [comment]
> @FotieMConstant , @TatchumNono :
> Considering to working on these, i found some files in the codebase and would love to hear from you if they necessarily should implement this pattern
> -Copyright.js -> CopyRight.js
> -serviceWorker.js -> ServiceWorker.js
> -setupTests.js -> SetupTests.js
> -Navbar.js -> NavBar.js

I personally think this naming convention is clean and good practice to work with, what do you say @marcosriani and @TatchumNono ?

**Review by TatchumNono — APPROVED** [review]
Hi, your right cause I think conflicts will arise when trying to merge

**Review by FotieMConstant — APPROVED** [review]
Hi, Thanks for your PR!

**Pull request merged**
