### PR TITLE
Integrate i18n in app

### LINKED ISSUE #11: Absence of i18n support
## Problem
The current app lacks the ability to present its content in languages other than English. This may render non-speaking English users uncomfortable to make proper use of the app in their LANs.

## Solution
Add internalization support using any best library that can easily integrate with react.

@FotieMConstant, @TatchumNono, @marcosriani

### PR DESCRIPTION
**Pull request by ayamba-coder**
Fixes #11 
Internalization now supported in LanTube-v2 with English and French as the available languages.
## French
i18n

## English
i18n-eng

## TODO:
Toggle component to be used for language switch at runtime.
House-keeping

@FotieMConstant @TatchumNono @marcosriani kindly review this my PR

### CODE REVIEW

**Review by FotieMConstant — APPROVED** [review]
Hi @ayamba-coder, thanks for this amazing PR. everything looks great! Please @marcosriani can you have a look at this PR before we merge!

PS: I was thinking. I think having a language toggle would be great as well!
Thanks!

**Comment by ayamba-coder** [comment]
@FotieMConstant yes look at my list of to-dos on the pr's comment(Toggle component to be used for language switch at runtime.) :)

**Review by TatchumNono — APPROVED** [review]
Hi, thanks for this amazing feature, I think it would be very useful

**Comment by ayamba-coder** [comment]
Could this request be merged,i have successfully done the language toggler which now toggles the app to different languages

@TatchumNono @TatchumNono @marcosriani

**Pull request merged**
